return {
    'github/copilot.vim', -- Install CoPilot that allows code suggestions/completions
    -- {
    --   'CopilotC-Nvim/CopilotChat.nvim',
    --   branch = 'canary',
    --   dependencies = {
    --     { 'zbirenbaum/copilot.lua' }, -- or github/copilot.vim
    --     { 'nvim-lua/plenary.nvim' }, -- for curl, log wrapper
    --   },
    --   opts = {
    --     debug = false, -- Enable debug logging
    --     proxy = nil, -- [protocol://]host[:port] Use this proxy
    --     allow_insecure = false, -- Allow insecure server connections
    --   },
    --   keys = {
    --     {
    --       desc = 'CopilotChat - Quick chat',
    --       '<leader>ccq',
    --       function()
    --         local input = vim.fn.input 'Quick Chat: '
    --         if input ~= '' then
    --           require('CopilotChat').ask(input, { selection = require('CopilotChat.select').buffer })
    --         end
    --       end,
    --     },
    --     -- Show help actions with telescope
    --     {
    --       '<leader>cch',
    --       function()
    --         local actions = require 'CopilotChat.actions'
    --         require('CopilotChat.integrations.telescope').pick(actions.help_actions())
    --       end,
    --       desc = 'CopilotChat - Help actions',
    --     },
    --     -- Show prompts actions with telescope
    --     {
    --       '<leader>ccp',
    --       function()
    --         local actions = require 'CopilotChat.actions'
    --         require('CopilotChat.integrations.telescope').pick(actions.prompt_actions())
    --       end,
    --       desc = 'CopilotChat - Prompt actions',
    --     },
    --   },
    -- },
}